Active auctions
Coflnet/hypixel-react pull request #298
Opened 2021-07-23 23:30 UTC by matthias-luger

fixes #296 
fixes #294
fixes #288
fixes #284
fixes #227

2021-07-23 23:51 UTC, Ekwav requested changes
- the filter is always set to `itemFilter=e30=` wich disabled all time
- active auctions can't be reached via direct link
- there is no sort order select on active auctions

2021-07-23 23:51 UTC, Ekwav commented on src/components/ActiveAuctions/ActiveAuctions.tsx
> +    let recentAuctionList = activeAuctions.map((recentAuction) => {
recentAuctions?

2021-07-23 23:51 UTC, Ekwav commented on src/components/ActiveAuctions/ActiveAuctions.tsx
> +                            <p>{'ended ' + moment(recentAuction.end).fromNow()}</p>
```suggestion
                            <p>{'ends ' + moment(recentAuction.end).fromNow()}</p>
```

2021-07-23 23:51 UTC, Ekwav commented on src/components/ItemFilter/ItemFilter.tsx
> +                    <DeleteIcon style={{marginLeft: "5px", top: "45px", position: "absolute"}} color="error" />
this overlaps with other filters if there are multiple

2021-07-23 23:52 UTC, Ekwav commented
Please also read the description of #227 you did only the thing in the title not the other 3 ;)

2021-07-24 04:18 UTC, matthias-luger commented
the feature to remember which tab was selected should be an own issue

2021-07-24 09:12 UTC, Ekwav requested changes
I miss the feature to link to active auctions directly. See #288 
like using `/item/{TAG}/active`

2021-07-24 09:44 UTC, Ekwav commented
Furthermore the copy button required by #227 is missing on active auctions

2021-07-24 14:43 UTC, matthias-luger commented
> I miss the feature to link to active auctions directly. See #288
> like using `/item/{TAG}/active`

Like I said in my other commend, please create a seperate issue

2021-07-24 14:45 UTC, Ekwav commented
> > I miss the feature to link to active auctions directly. See #288
> > like using `/item/{TAG}/active`
> 
> Like I said in my other commend, please create a seperate issue

Then please remove "fixes #288" as this PR does not fix it.

2021-07-24 23:17 UTC, Ekwav approved these changes
I hope nothing broke

2021-07-24 23:17 UTC, merged

2021-07-25 04:33 UTC, Ekwav requested changes

2021-07-25 04:33 UTC, Ekwav commented on src/utils/Formatter.tsx
> +            color = tierColors[tier]
This is missing a -1